name: calculate-weeks

on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

jobs:
  check_repo_commits:
    runs-on: self-hosted
    env:
      TEST_REPO_URL: https://github.com/VladimirBrejcha/Rise.git
    steps:
      - name: Run a multi-line script
        run: |
          git clone ${{ env.TEST_REPO_URL }} projectFolder
          cd Rise
          git log --format=%cd
          cd ../
          rm -rf $GITHUB_WORKSPACE/projectFolder
