name: Calculate weeks

on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

jobs:
  check_repo_commits:
    runs-on: self-hosted
    env:
      TEST_DATE: 01:01:2021
      TEST_REPO: Rise
      TEST_AUTHOR: VladimirBrejcha
    steps:
      - name: Fetch repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get commit dates
        run: 
          swift ${GITHUB_WORKSPACE}/GetCommitDates.swift -since $TEST_DATE -repo $TEST_REPO -author $TEST_AUTHOR
