name: calculate-weeks

on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

jobs:
  check_repo_commits:
    runs-on: self-hosted
    env:
      TEST_DATE: 01:01:2021
      TEST_REPO: Rise
      TEST_AUTHOR: VladimirBrejcha
    steps:
      - name: Run a multi-line script
        run: 
          swift ${GITHUB_WORKSPACE}/GetCommitDates.swift -since $01:01:2021 -repo $Rise -author $VladimirBrejcha
