# - name: GitHub Script
#   uses: actions/github-script@v4.1.0
#   with:
#     # The script to run
#     script: 
#     # The GitHub token used to create an authenticated client
#     github-token: # optional, default is ${{ github.token }}
#     # Whether to tell the GitHub client to log details of its requests
#     debug: # optional
#     # An optional user-agent string
#     user-agent: # optional, default is actions/github-script
#     # A comma-separated list of API previews to accept
#     previews: # optional
#     # Either "string" or "json" (default "json")—how the result will be encoded
#     result-encoding: # optional, default is json

name: calculate-weeks

on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

jobs:

  check_repo_commits:
    runs-on: self-hosted
    env:
      TEST_REPO_URL: https://github.com/VladimirBrejcha/Rise.git
    steps:
      - name: Run a multi-line script
        run: |
          git clone env.TEST_REPO_URL
          cd Rise
          git log --format=%cd
